version: '3.8'

services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8800"]
    volumes:
      - .:/app
    ports:
      - "8800:8800"
    environment:
      - DEBUG
      - SECRET_KEY
      - ALLOWED_HOSTS
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
