# Generated by Django 5.0.6 on 2024-06-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]
# data_users , data_account , data_sessions , orders , order_items , payments, reviews
    operations = [
        migrations.RunSQL(
            sql="""
                DROP TABLE IF EXISTS reviews;
                DROP TABLE IF EXISTS payments;
                DROP TABLE IF EXISTS order_items;
                DROP TABLE IF EXISTS orders;
                DROP TABLE IF EXISTS data_sessions;
                DROP TABLE IF EXISTS data_account;
                DROP TABLE IF EXISTS data_users;
            """,
        )
    ]
